moneyhub/moneyhub-api-client

src/__tests__/accounts.js
The accounts smoke tests now use config values to get the test account Id and test pension ID to improve robustness.
=> Accounts tests use config values

src/index.js
This is deprecated & you have the correct API usage on line 50
https://github.com/moneyhub/moneyhub-api-client/blob/399418d0879570f5a2069351c4d7a3f6db117c1d/src/index.js#L50
=> refactor: remove deprecated defaultHttpOptions assignment

readme.md, src/get-auth-urls.js
This allows for the AIS consent options laid out [here](https://docs.moneyhubenterprise.com/docs/ais-consents) to be passed as arguments in the authorisation URL generation methods.
=> Add AIS consent options to auth URL

examples/auth/get-authorize-url-for-user.js, examples/auth/get-authorize-url.js, examples/auth/get-reauth-authorize-url-for-user.js, examples/auth/get-refresh-authorize-url-for-user.js, examples/user/get-connection-syncs.js, examples/user/get-sync.js, readme.md, src/__tests__/index.js, src/get-auth-urls.js, src/requests/users-and-connections.js
This PR adds the following:
- Methods for getting:
- a connection's syncs
- a specific sync by ID
- Allowing to pass `enableAsync` into the get auth URL methods
=> Sync end points

examples/connections/update-connection.js, readme.md, src/__tests__/index.js, src/requests/users-and-connections.js
Adds a `updateUserConnection` method to the API client for the `PATCH /user/:userId/connections/:connectionId` endpoint. Currently only used to update the `expiresAt` field to renew consent on a connection.
=> Add update connection method MH3-8035

examples/auth/get-reconsent-authorize-url-for-user.js, src/__tests__/auth-urls.js, src/__tests__/index.js, src/get-auth-urls.js
Description: 
Adds a method to create a URL to redirect a user for renewing consent on a connection.
=> Add getReconsentAuthorizeUrlForCreatedUser method MH3-7764

examples/payments/get-reverse-payment-authorization-url.js, readme.md, src/get-auth-urls.ts, types/get-auth-urls.ts
- Allows for reverse payment payer to be specified when making an auth URL for a reverse payment
- get-auth-urls file updated to be typescript to allow for better typing
=> Reverse payment payer can be specified

CHANGELOG.md, examples/accounts/get-account-counterparties.js, examples/auth-requests/create-payment.js, examples/auth-requests/create-standing-order.js, readme.md, src/__tests__/accounts.ts, src/__tests__/auth-urls.ts, src/get-auth-urls.ts, src/request.ts, src/requests/accounts.ts, src/requests/types/accounts.ts, src/schema/payee.ts
MH3-9370
This change adds a version param for counterparties
This change adds the ability to replace a payeeId with payee in auth-requests.
Tests updated / added
=> Add payeeless payments and version for counterparties

src/__tests__/accounts.ts, src/__tests__/index.ts, src/requests/accounts.ts, src/requests/types/accounts.ts, src/schema/account.ts
This adds the following routes to the API client:
- `PATCH /accounts/:accountId`
- `POST /accounts/:accountId/balances`
=> Add routes for patch account and post account balances

examples/accounts/get-accounts-list-with-details.js, examples/accounts/get-accounts-list.js, package-lock.json, readme.md, src/__tests__/accounts.ts, src/__tests__/index.ts, src/requests/accounts.ts, src/requests/types/accounts.ts
Adds method for new /accounts-list endpoint which doesn't return transactionData and performanceScore by default.
=> Add getAccountsList methods MH3-10323

src/get-auth-urls.ts
Previously the PAR URL method would create a URL with query parameters like `response_type` in the URL, and sometimes this value wouldn't match the config of the client (it would always default to `code`)
This just makes the URL have a `request_uri` query parameter.
=> Use simple URL for PAR

src/__tests__/index.ts, src/__tests__/regular-transactions.ts, src/requests/regular-transactions.ts, src/requests/types/regular-transactions.ts
API-163
This change adds the regular transaction detect functionality. 
Works just like the get regular transactions but requires an accountId instead of it being optional and hits the detect endpoint.
=> Add regular transaction detect

src/__tests__/request.ts, src/request.ts
API-379
This change adds functionality to add a version to your API urls. 
With no version it defaults to v3, if you add a version to the URL then it will use this, if you add a version in options it will use this next.
Identity urls are specifically checked for and untouched.
Tests were written by my good friend co-pilot, and seem to be pretty solid!
=> Add automatic versioning to api urls with customisation

src/__tests__/request.ts, src/request.ts
API-379
This change improves upon the versioning in the client and will splice the version into the URL when using a path.
=> Add splicing of version to the urls

package-lock.json, package.json, src/__tests__/index.ts, src/schema/config.ts
Breaking changes:
[jose](https://github.com/panva/jose/releases/tag/v5.0.0)
[openid-client](https://github.com/panva/node-openid-client/releases/tag/v5.0.0)
- End-Of-Life versions of Node.js as of October 2023 - will have to update readme/docs to show compatibility with node 18+
=> Update jose and OIDC client

readme.md, src/get-auth-urls.ts, src/schema/payee.ts, src/schema/payment.ts
- Adds `payer` to claims
- Creates `PayerType` interface for differentiating between payer and payee types
=> Add payerType: api-payer and payer to payment claims

src/schema/payment.ts
Changes:
- Updated types for RecurringPaymentRequest
=> PAY-469-updated-types-for-recurring-payments

src/schema/config.ts
Make the `client_secret` on `ApiClientConfig` optional.
I believe it is not necessary to provide the secret when using jwks, can anyone confirm?
=> Make client secret optional in ApiClientConfig

src/tokens.ts
The README specifies that `sub` is optional when calling `getClientCredentialTokens` but the typing forces one to be provided.
This PR makes it optional.
https://github.com/moneyhub/moneyhub-api-client#getclientcredentialtokens
>Use this to get a client credentials access token.
```
const tokens = await moneyhub.getClientCredentialTokens({
scope: "the-required-scope",
sub: "the user id", // optional
});
```
=> Make sub optional in getClientCredentialTokens

src/__tests__/categories.ts
- Makes the get business category test independent of the previous tests
- Changes get categories to be less strict about exact number of business categories
=> API-1237 Fix categories test

examples/token/create-jwt-bearer-grant-token.js, src/tokens.ts
Small bug:
There was an issue where the `sub` value in the JWT was nested incorrectly.
Now, after fix - `sub` passed correctly.
Also, it should generate JWT by `clientId` and not `userId`. So this was fixed as well.
=> API-1217 sub fix

readme.md, src/index.ts, src/request.ts, src/schema/config.ts
This allows to control retry options for all requests
This functionality was useful when running the [transaction categorisation ETL](https://github.com/moneyhub/categorisation-etl) to retry posting transactions when there is a gateway error
API-1258
=> Add retry options

readme.md, src/__tests__/accounts.ts, src/__tests__/index.ts, src/requests/types/unauthenticated.ts, src/requests/unauthenticated.ts
Some endpoints are only available in V2 
This updates the tests to force the request to use V2 when appropriate regardless of the config
=> SHOW: Update tests using version option
